apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-modia-kontakt-metrikk
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - https://flexmodia-kontakt.intern.dev.nav.no
  liveness:
    path: /internal/health/liveness
  readiness:
    path: /internal/health/readiness
  startup:
    path: /internal/health/liveness
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: {{kafkaPool}}
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: flex-modia-kontakt-metrikk-db
            envVarPrefix: DATABASE
            users:
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
