environment: prod
replicas_min: 1
replicas_max: 1
cpu: 100m
memory: 600Mi
db_tier: db-custom-1-3840
db_highAvailability: true
db_pointInTimeRecovery: true
kafkaPool: nav-prod
env:
  SPRING_PROFILES_ACTIVE: default
